hydra:
  job:
    chdir: False

train:
  dataset_name: ["JasiekKaczmarczyk/giant-midi-sustain-quantized"] # huggingface dataset
  batch_size: 16
  num_workers: 8
  lr: 3e-4
  weight_decay: 0.01
  pitch_shift_probability: 0.5
  time_stretch_probability: 0.5
  num_epochs: 1000
  device: "cuda"
  precision: "16-mixed" # not implemented yet
  overfit_single_batch: True

quantization:
  dstart_bin: 7
  duration_bin: 7
  velocity_bin: 7

paths:
  save_ckpt_dir: "checkpoints" # directory where checkpoints will be saved
  load_ckpt_path: null # if not None, specifies path to model state dict which will be loaded
  log_dir: "logs"
  hf_repo_id: null # repo id to upload model to huggingface if null model is not uploaded

logger:
  run_name: overfit-single-batch-${now:%Y-%m-%d-%H-%M}
  log_every_n_steps: 1
