hydra:
  job:
    chdir: False

train:
  dataset_name: ["JasiekKaczmarczyk/giant-midi-sustain-masked", "JasiekKaczmarczyk/pianofor-ai-sustain-masked", "JasiekKaczmarczyk/maestro-v1-sustain-masked"] # huggingface dataset
  batch_size: 168
  num_workers: 8
  lr: 1e-5
  weight_decay: 0.01
  pitch_shift_probability: 0.5
  time_stretch_probability: 0.5
  num_epochs: 5
  max_tokens_processed: null
  device: "cuda"
  precision: "16-mixed" # not implemented yet
  overfit_single_batch: False

quantization:
  dstart_bin: 7
  duration_bin: 3
  velocity_bin: 3

paths:
  save_ckpt_dir: "checkpoints" # directory where checkpoints will be saved
  load_ckpt_path: null # if not None, specifies path to model state dict which will be loaded
  log_dir: "logs"
  hf_repo_id: null # repo id to upload model to huggingface if null model is not uploaded

logger:
  run_name: masked-midi-modelling-${now:%Y-%m-%d-%H-%M}
  log_every_n_steps: 25
